name: Genera Documentazione Aggiornata

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync-upstream:
    uses: ./.github/workflows/sync-upstream.yaml

  update-python-api:
    needs: sync-upstream
    uses: ./.github/workflows/__update-adk-python-api.yml

  publish-docs:
    needs: update-python-api
    uses: ./.github/workflows/publish-docs.yaml

  release-docs:
    needs: publish-docs
    uses: ./.github/workflows/release-docs.yaml
